const gear = [
  { name: 'Superblast 2', miles: 347, use: 'Mostly long & easy runs', role: 'Daily / long' },
  { name: 'Adios Pro 4', miles: 126, use: 'Mostly races & workouts', role: 'Race' },
  { name: 'Cloudboom Strike', miles: 82, use: 'Mostly speed workouts', role: 'Speed' }
];
const shoes = [
  { name: 'ASICS Gel-Nimbus 27', brand: 'ASICS', price: 180, match: 94, tags: ['Long run', 'Cushioned', 'Marathon'], image: 'assets/ASICS%20Gel-Nimbus%2027%20.png', url: 'https://www.asics.com/sg/en-sg/mk/running/nimbus27', reason: 'Adds a protective long-run role without duplicating your speed or race shoes.', detail: 'A cushioned long-run complement that can gradually take pressure off the Superblast 2.' },
  { name: 'Saucony Triumph 22', brand: 'Saucony', price: 160, match: 89, tags: ['Long run', 'Soft', 'Daily'], image: 'assets/Saucony%20Triumph%2022%20.webp', url: 'https://www.saucony.com/en/triumph-22/', reason: 'Creates a softer, durable lane for easy and long days.', detail: 'Adds relaxed-mileage comfort while your faster shoes retain their distinct jobs.' },
  { name: 'New Balance Fresh Foam X 1080v14', brand: 'New Balance', price: 165, match: 86, tags: ['Long run', 'Cushioned', 'Easy'], image: 'assets/New%20Balance%20Fresh%20Foam%20X%201080v14%20.jpg', url: 'https://www.newbalance.com/pd/fresh-foam-x-1080v14/M1080V14-47512-PMG-NA-US-BROWN.html', reason: 'Brings smooth cushioning for easy volume and longer efforts.', detail: 'Fills the long-run comfort role with enough versatility for easy daily mileage.' }
];
const state = { prompt: '', turns: [], connected: false, connectionTurn: false, screen: 'conversation', selected: shoes[0], activity: null, revealed: 0, storeFinderOpen: false, zip: '', stores: [], conversationScrollY: 0 };
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const app = document.querySelector('#app');
const header = () => `<header><strong>RUNNING SCOUT</strong><span class="avatar">N</span></header>`;
const mark = () => '<span class="scout-mark">✦</span>';
const starterPrompts = () => ['Long runs', 'Race day', 'Daily miles', 'Replace a shoe'].map(label => `<button data-prompt="I need help with ${label.toLowerCase()}.">${label}</button>`).join('');
const scout = (label, content, type = '') => `<article class="chat-turn scout-turn ${type}">${mark()}<div><p class="speaker">${label}</p>${content}</div></article>`;
const user = prompt => `<article class="chat-turn user-turn"><p class="speaker">YOU ASKED</p><p>${prompt}</p></article>`;

function welcome() { return scout('SCOUT', `<h1>Let’s find your next shoe.</h1><p>Tell me what you’re training for, what feels missing, or what needs replacing.</p><button class="connect-inline" data-action="strava">✦ Connect Strava <span>Use sample activity &amp; gear data →</span></button>`, 'welcome-turn'); }
function connectedContext() { return scout('SCOUT · SAMPLE STRAVA DATA', `<h2>I have your current rotation.</h2><p>This prototype is using sample connected gear, so I can factor in mileage and shoe roles.</p><div class="rotation-chips">${gear.map(item => `<span>${item.name} · ${item.miles} mi</span>`).join('')}</div><p>Your speed and race-day shoes are covered. The Superblast 2 is at <strong>347 miles</strong>, so a long-run successor is the most useful next category to investigate.</p><div class="scout-actions"><button data-action="long-run">Find a long-run option</button><button data-action="something-else">I’m looking for something else</button></div>`, 'observation-turn'); }
function evidence() { const items = state.connected ? '<span>✓ Sample rotation & mileage</span><span>✓ Speed/race coverage</span><span>✓ Long-run gap</span>' : '<span>✓ Your stated request</span><span>✓ Product role filters</span><span>✓ Price reference</span>'; return `<section class="evidence"><p class="speaker">WHAT I USED</p><div>${items}<span>✓ 24 eligible shoes compared</span></div></section>`; }
function investigation() { const description = state.connected ? 'I checked the sample rotation, mileage, shoe roles, and catalog eligibility.' : 'I used your stated request and product role filters. You can connect Strava if you want Scout to check sample mileage and rotation coverage.'; const steps = state.connected ? '<span>✓ Checked rotation coverage</span><span>✓ Reviewed sample mileage</span>' : '<span>✓ Interpreted your request</span><span>✓ Filtered relevant shoe roles</span>'; return scout('SCOUT IS INVESTIGATING', `<h2>Looking into that now.</h2><p>${description}</p><div class="investigation">${steps}<span>✓ Compared 24 eligible shoes</span><span>✓ Found 3 strong fits</span></div>`, 'investigation-turn'); }
function product(shoe) { return `<article class="inline-product"><div class="product-image"><img src="${shoe.image}" alt="${shoe.name}" /></div><div class="product-copy"><p class="match">${shoe.match}% MATCH · ${shoe.tags.join(' · ')}</p><div class="product-name"><h3>${shoe.name}</h3><strong>$${shoe.price}</strong></div><p>${shoe.reason}</p><button data-action="detail-${shoe.name}">Why Scout picked it <b>→</b></button></div></article>`; }
function recommendations() { const summary = state.connected ? 'These add long-run comfort without duplicating the speed and race-day roles in your sample rotation.' : 'These are strong candidates for the need you described. Connect Strava to compare them against sample rotation data.'; return scout('SCOUT FOUND 3 OPTIONS', `<h2>These are worth a look.</h2><p>${summary}</p>${evidence()}<div class="inline-products">${shoes.map((shoe, index) => `<div class="result-reveal result-${index}">${product(shoe)}</div>`).join('')}</div>`, 'recommendation-turn result-reveal result-finding'); }
function activityTurn() { if (!state.activity) return ''; const steps = ['Checking your rotation', 'Comparing long-run shoes']; const current = Math.min(state.activity.step, steps.length - 1); return scout('SCOUT IS WORKING', `<h2>${steps[current]}…</h2><div class="activity-steps">${steps.map((step, index) => `<span class="${index < current ? 'complete' : index === current ? 'active' : ''}">${index < current ? '✓' : index === current ? '✦' : '○'} ${step}</span>`).join('')}</div>`, 'activity-turn'); }
function requestTurns() { if (!state.turns.length) return ''; const prior = state.turns.slice(0, -1).flatMap(prompt => [user(prompt), investigation(), recommendations()]).join(''); const latest = user(state.turns[state.turns.length - 1]); if (state.activity) return `${prior}${latest}${activityTurn()}`; return `${prior}${latest}${investigation()}${recommendations()}`; }
function transcript() { if (!state.connected && !state.turns.length) return welcome(); const connected = state.connected && state.connectionTurn ? connectedContext() : ''; return `${connected}${requestTurns()}`; }
function composer() { const activeConversation = state.connected || state.turns.length; const connectedContext = state.connected && state.connectionTurn && !state.turns.length; const placeholder = connectedContext ? 'Or tell Scout what you need…' : activeConversation ? 'Ask Scout to refine the results…' : 'Tell Scout what you need…'; const helper = state.connected ? 'Scout can use the connected sample rotation, mileage, goals, and product catalog.' : 'Connect Strava to let Scout use sample rotation and mileage data in this prototype.'; const label = connectedContext ? '✦ Your next move' : activeConversation ? '✦ Ask Scout' : '✦ What are we looking for today?'; return `<form id="conversation-composer" class="composer persistent-composer"><label for="prompt">${label}</label><div><span>✦</span><input id="prompt" value="${state.prompt}" placeholder="${placeholder}" aria-label="Message Scout" /><button aria-label="Ask Scout">→</button></div><small>${helper}</small>${activeConversation ? '' : `<div class="prompt-suggestions" aria-label="Starter prompts">${starterPrompts()}</div>`}</form>`; }
function conversation() { return `<section class="workspace">${header()}<main class="conversation-shell"><section class="conversation-thread">${transcript()}</section>${composer()}</main></section>`; }
function importedGear() { return `${header()}<main class="simple-flow"><button class="back" data-action="conversation">← Back to Scout</button>${scout('SCOUT IMPORTED SAMPLE DATA', `<h2>I found your sample running shoes.</h2><p>Confirming this lets Scout use mileage and rotation roles without losing anything you already asked.</p>`)}${gear.map(item => `<article class="gear-card"><b>${item.name}</b><span>${item.miles} miles · ${item.use}</span><em>✓ This looks right</em></article>`).join('')}<button class="continue" data-action="confirm-gear">Use this sample rotation →</button></main>`; }
function sampleStores(zip) { return [{ name: 'Fleet Feet Downtown', distance: '1.2 mi', address: '123 Main Street, Sample City', phone: '(555) 010-2040' }, { name: 'Run Specialty Co.', distance: '2.8 mi', address: '480 Park Avenue, Sample City', phone: '(555) 010-1182' }, { name: 'The Running Shop', distance: '4.5 mi', address: '822 Market Street, Sample City', phone: '(555) 010-0957' }].map(store => ({ ...store, zip })); }
function storeFinder(shoe) { if (!state.storeFinderOpen) return ''; const results = state.stores.length ? `<div class="store-results"><p class="sample-results">Sample store results — not live inventory</p>${state.stores.map(store => `<article class="store-card"><div><h3>${store.name} <small>Sample</small></h3><span class="store-distance">${store.distance}</span></div><p>${store.address}</p><p class="availability">Size availability unconfirmed — contact store</p><div class="store-actions"><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${store.name}, ${store.address}, ${store.zip}`)}">Directions ↗</a><a href="tel:${store.phone.replace(/[^0-9+]/g, '')}">Call ${store.phone}</a></div></article>`).join('')}</div>` : '<p class="store-empty">Enter a ZIP code to see prototype nearby-store results. Store data and availability are not live.</p>'; return `<section class="store-finder"><div class="finder-heading"><div><p class="speaker">FIND IN STORES</p><h2>Try ${shoe.name} nearby</h2><p>Sample store results for this prototype. Availability is not connected to live inventory.</p></div><button class="close-finder" data-action="close-stores" aria-label="Close store finder">×</button></div><form id="store-search" class="zip-form"><label for="zip">ZIP code</label><div><input id="zip" inputmode="numeric" pattern="[0-9]{5}" maxlength="5" value="${state.zip}" placeholder="e.g. 94103" aria-label="ZIP code" /><button>Search</button></div></form><div class="map-panel" aria-label="Prototype map"><span>MAP PREVIEW</span><strong>Nearby running stores</strong><small>Open directions for live map navigation.</small></div>${results}</section>`; }
function detail() { const shoe = state.selected; const context = state.connected ? 'sample rotation' : 'stated request'; const fit = state.connected ? `<p class="speaker">YOUR ROTATION ALREADY COVERS</p><div><span>Speed sessions</span><b>✓</b></div><div><span>Race day</span><b>✓</b></div><p class="speaker fit-adds">THIS SHOE ADDS</p><div class="fills"><span>Cushioned long runs</span><b>← Fills the gap</b></div>` : `<p class="speaker">THIS SHOE ADDS</p><div><span>Long-run cushioning</span><b>✓</b></div><div><span>Requested role fit</span><b>✓</b></div><p class="fit-note">Connect sample rotation data to verify how it complements your current shoes.</p>`; return `${header()}<main class="detail"><button class="back" data-action="conversation">← Back to conversation</button><div class="detail-context">${mark()}<span>Scout is keeping your ${context} in context.</span></div><div class="detail-image"><img src="${shoe.image}" alt="${shoe.name}" /><small>Product image</small></div>${scout('SCOUT’S MATCH', `<h2>${shoe.name}</h2><p>${shoe.detail}</p>`)}<section class="fit">${fit}</section><section class="buy"><strong>$${shoe.price}<small>reference price</small></strong><a class="cta lime" target="_blank" rel="noopener" href="${shoe.url}">BUY ONLINE <b>↗</b></a><button class="find-stores" data-action="open-stores">Find in stores</button><button class="ask" data-action="conversation">Refine with Scout</button></section>${storeFinder(shoe)}</main>`; }
function render() { app.innerHTML = `<div class="phone">${state.screen === 'detail' ? detail() : state.screen === 'importedGear' ? importedGear() : conversation()}</div>`; bind(); if (state.screen === 'conversation' && state.conversationScrollY) requestAnimationFrame(() => { window.scrollTo({ top: state.conversationScrollY, behavior: 'auto' }); state.conversationScrollY = 0; }); }
function appendRequest(value) { const text = value.trim(); if (!text) return; state.prompt = ''; state.turns.push(text); state.activity = { step: 0 }; render(); requestAnimationFrame(() => document.querySelector('.activity-turn')?.scrollIntoView({ behavior: reducedMotion ? 'auto' : 'smooth', block: 'nearest' })); const delay = reducedMotion ? 0 : 1200; const advance = () => { if (!state.activity) return; if (state.activity.step === 0) { state.activity.step = 1; render(); setTimeout(advance, delay); return; } state.activity = null; state.revealed += 1; render(); requestAnimationFrame(() => document.querySelector('.recommendation-turn')?.scrollIntoView({ behavior: reducedMotion ? 'auto' : 'smooth', block: 'nearest' })); }; setTimeout(advance, delay); }
function bind() { app.querySelectorAll('[data-action]').forEach(element => element.onclick = () => { const action = element.dataset.action; if (action === 'strava') state.screen = 'importedGear'; else if (action === 'confirm-gear') { state.connected = true; state.connectionTurn = true; state.prompt = ''; state.screen = 'conversation'; } else if (action === 'long-run') appendRequest('Find a long-run option.'); else if (action === 'something-else') { state.prompt = ''; state.screen = 'conversation'; render(); requestAnimationFrame(() => document.querySelector('#prompt')?.focus()); return; } else if (action === 'open-stores') { state.storeFinderOpen = true; state.stores = []; } else if (action === 'close-stores') { state.storeFinderOpen = false; } else if (action === 'conversation') { state.screen = 'conversation'; } else if (action.startsWith('detail-')) { state.conversationScrollY = window.scrollY; state.selected = shoes.find(shoe => shoe.name === action.slice(7)) || shoes[0]; state.storeFinderOpen = false; state.screen = 'detail'; } render(); }); app.querySelectorAll('[data-prompt]').forEach(element => element.onclick = () => { state.prompt = element.dataset.prompt; render(); document.querySelector('#prompt')?.focus(); }); const form = app.querySelector('#conversation-composer'); if (form) form.onsubmit = event => { event.preventDefault(); appendRequest(app.querySelector('#prompt').value); }; const storeSearch = app.querySelector('#store-search'); if (storeSearch) storeSearch.onsubmit = event => { event.preventDefault(); const zip = app.querySelector('#zip').value.trim(); if (!/^\d{5}$/.test(zip)) { app.querySelector('#zip').setCustomValidity('Enter a 5-digit ZIP code.'); app.querySelector('#zip').reportValidity(); return; } state.zip = zip; state.stores = sampleStores(zip); render(); }; }
render();
